-- ==========================================
-- 0. LIMPIEZA DEL ENTORNO
-- ==========================================

BEGIN
   -- Recorrer todas las tablas que pertenecen al usuario actual
   FOR rec IN (SELECT table_name FROM user_tables) LOOP
      -- Ejecutar el comando DROP para cada tabla encontrada
      -- CASCADE CONSTRAINTS: Borra las claves foráneas que apuntan a esta tabla
      -- PURGE: Borra la tabla definitivamente
      EXECUTE IMMEDIATE 'DROP TABLE "' || rec.table_name || '" CASCADE CONSTRAINTS PURGE';
   END LOOP;
   
   DBMS_OUTPUT.PUT_LINE('Todas las tablas han sido eliminadas correctamente.');
EXCEPTION
   WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('Error al intentar borrar las tablas: ' || SQLERRM);
END;


-- =========================================================
-- 1. CREACIÓN. TABLAS DE DIMENSIONES
-- =========================================================

CREATE TABLE Dim_Date (
    date_sk         DATE PRIMARY KEY, -- PK es el valor de la fecha
    day_of_month    NUMBER(2),
    day_of_week     VARCHAR2(15),
    is_weekend      CHAR(1) CHECK (is_weekend IN ('Y', 'N')),
    month_name      VARCHAR2(15),
    quarter         NUMBER(1),
    year            NUMBER(4),
    week_of_year    NUMBER(2)
);

CREATE TABLE Dim_Time (
    time_sk         VARCHAR2(8) PRIMARY KEY, -- PK formato 'HH24:MI:SS'
    hour            NUMBER(2),
    minute          NUMBER(2),
    second          NUMBER(2)
);

CREATE TABLE Dim_Viewer (
    viewer_sk       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_viewer       VARCHAR2(50) NOT NULL,
    gender          VARCHAR2(20),
    country         VARCHAR2(50),
    birthdate       DATE
);

CREATE TABLE Dim_Channel (
    channel_sk       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_channel       VARCHAR2(50) NOT NULL,
    primary_language VARCHAR2(30)
);

CREATE TABLE Dim_Streaming_Session (
    session_sk           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_streaming_session VARCHAR2(50) NOT NULL,
    title                VARCHAR2(255),
    language             VARCHAR2(30)
);

CREATE TABLE Dim_Activity (
    activity_sk     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_activity     VARCHAR2(50) NOT NULL,
    activity_name   VARCHAR2(100), -- solo para juegos, sino NO_APLICA
    collection_name VARCHAR2(100),
    directory_name  VARCHAR2(100)
);

CREATE TABLE Dim_Junk_Status (
    junk_status_sk  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isLoggedIn      CHAR(1) CHECK (isLoggedIn IN ('Y', 'N')),
    isSubbed        CHAR(1) CHECK (isSubbed IN ('Y', 'N')),
    follows_channel CHAR(1) CHECK (follows_channel IN ('Y', 'N'))
);

CREATE TABLE Dim_Viewer_Channel_Role (
    role_sk              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    viewer_sk            NUMBER,
    channel_sk           NUMBER,
    role_name            VARCHAR2(50),
    effective_start_date DATE,
    effective_end_date   DATE,
    is_current           CHAR(1) CHECK (is_current IN ('Y', 'N'))
);

-- =========================================================
-- 2. CREACIÓN. TABLAS DE APOYO (BRIDGE)
-- =========================================================

CREATE TABLE Dim_Activity_Group (
    activity_group_sk NUMBER PRIMARY KEY,
    group_name        VARCHAR2(100)
);

CREATE TABLE Bridge_Activity_Group (
    activity_group_sk NUMBER,
    activity_sk       NUMBER,
    weighting_factor  NUMBER(5, 4),
    PRIMARY KEY (activity_group_sk, activity_sk)
);

-- =========================================================
-- 3. CREACIÓN. TABLAS DE HECHOS 
-- =========================================================

CREATE TABLE Fact_View (
    view_sk              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    viewer_sk            NUMBER,
    channel_sk           NUMBER,
    session_sk           NUMBER,
    activity_group_sk    NUMBER,
    -- Referencias a Dim_Date (DATE)
    start_date_local_sk  DATE,
    end_date_local_sk    DATE,
    start_date_utc_sk    DATE,
    end_date_utc_sk      DATE,
    -- Referencias a Dim_Time (VARCHAR2)
    start_time_local_sk  VARCHAR2(8),
    end_time_local_sk    VARCHAR2(8),
    start_time_utc_sk    VARCHAR2(8),
    end_time_utc_sk      VARCHAR2(8),
    -- Junk Status
    start_junk_status_sk NUMBER,
    end_junk_status_sk   NUMBER,
    duration_minutes     NUMBER(10, 2)
);

CREATE TABLE Fact_Interaction (
    interaction_sk      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    viewer_sk           NUMBER,
    channel_sk          NUMBER,
    session_sk          NUMBER,
    activity_sk         NUMBER,
    date_local_sk       DATE,
    time_local_sk       VARCHAR2(8),
    date_utc_sk         DATE,
    time_utc_sk         VARCHAR2(8),
    interaction_type    VARCHAR2(10), -- follow, sub, cheer, unsub, unfollow
    revenue             NUMBER(19, 4)
);

-- =========================================================
-- 4. CREACIÓN. CLAVES FORÁNEAS
-- =========================================================

-- Hechos: Fact_View
ALTER TABLE Fact_View ADD CONSTRAINT fk_view_viewer FOREIGN KEY (viewer_sk) REFERENCES Dim_Viewer(viewer_sk);
ALTER TABLE Fact_View ADD CONSTRAINT fk_view_channel FOREIGN KEY (channel_sk) REFERENCES Dim_Channel(channel_sk);
ALTER TABLE Fact_View ADD CONSTRAINT fk_view_session FOREIGN KEY (session_sk) REFERENCES Dim_Streaming_Session(session_sk);
ALTER TABLE Fact_View ADD CONSTRAINT fk_view_act_group FOREIGN KEY (activity_group_sk) REFERENCES Dim_Activity_Group(activity_group_sk);

-- Referencias Temporales (DATE y VARCHAR2)
ALTER TABLE Fact_View ADD CONSTRAINT fk_view_date_start_loc FOREIGN KEY (start_date_local_sk) REFERENCES Dim_Date(date_sk);
ALTER TABLE Fact_View ADD CONSTRAINT fk_view_date_end_loc   FOREIGN KEY (end_date_local_sk)   REFERENCES Dim_Date(date_sk);
ALTER TABLE Fact_View ADD CONSTRAINT fk_view_date_start_utc FOREIGN KEY (start_date_utc_sk)   REFERENCES Dim_Date(date_sk);
ALTER TABLE Fact_View ADD CONSTRAINT fk_view_date_end_utc   FOREIGN KEY (end_date_utc_sk)     REFERENCES Dim_Date(date_sk);

ALTER TABLE Fact_View ADD CONSTRAINT fk_view_time_start_loc FOREIGN KEY (start_time_local_sk) REFERENCES Dim_Time(time_sk);
ALTER TABLE Fact_View ADD CONSTRAINT fk_view_time_end_loc   FOREIGN KEY (end_time_local_sk)   REFERENCES Dim_Time(time_sk);
ALTER TABLE Fact_View ADD CONSTRAINT fk_view_time_start_utc FOREIGN KEY (start_time_utc_sk)   REFERENCES Dim_Time(time_sk);
ALTER TABLE Fact_View ADD CONSTRAINT fk_view_time_end_utc   FOREIGN KEY (end_time_utc_sk)     REFERENCES Dim_Time(time_sk);

-- Referencias Junk Status
ALTER TABLE Fact_View ADD CONSTRAINT fk_view_junk_start FOREIGN KEY (start_junk_status_sk) REFERENCES Dim_Junk_Status(junk_status_sk);
ALTER TABLE Fact_View ADD CONSTRAINT fk_view_junk_end   FOREIGN KEY (end_junk_status_sk)   REFERENCES Dim_Junk_Status(junk_status_sk);


-- Hechos: Fact_Interaction
ALTER TABLE Fact_Interaction ADD CONSTRAINT fk_int_viewer  FOREIGN KEY (viewer_sk)  REFERENCES Dim_Viewer(viewer_sk);
ALTER TABLE Fact_Interaction ADD CONSTRAINT fk_int_channel FOREIGN KEY (channel_sk) REFERENCES Dim_Channel(channel_sk);
ALTER TABLE Fact_Interaction ADD CONSTRAINT fk_int_session FOREIGN KEY (session_sk) REFERENCES Dim_Streaming_Session(session_sk);
ALTER TABLE Fact_Interaction ADD CONSTRAINT fk_int_activity FOREIGN KEY (activity_sk) REFERENCES Dim_Activity(activity_sk);

-- Referencias Temporales en Interaction
ALTER TABLE Fact_Interaction ADD CONSTRAINT fk_int_date_loc FOREIGN KEY (date_local_sk) REFERENCES Dim_Date(date_sk);
ALTER TABLE Fact_Interaction ADD CONSTRAINT fk_int_date_utc FOREIGN KEY (date_utc_sk) REFERENCES Dim_Date(date_sk);
ALTER TABLE Fact_Interaction ADD CONSTRAINT fk_int_time_loc FOREIGN KEY (time_local_sk) REFERENCES Dim_Time(time_sk);
ALTER TABLE Fact_Interaction ADD CONSTRAINT fk_int_time_utc FOREIGN KEY (time_utc_sk) REFERENCES Dim_Time(time_sk);


-- Dim_Viewer_Channel_Role (SCD2)
ALTER TABLE Dim_Viewer_Channel_Role ADD CONSTRAINT fk_role_viewer  FOREIGN KEY (viewer_sk)  REFERENCES Dim_Viewer(viewer_sk);
ALTER TABLE Dim_Viewer_Channel_Role ADD CONSTRAINT fk_role_channel FOREIGN KEY (channel_sk) REFERENCES Dim_Channel(channel_sk);

-- Bridge_Activity_Group
ALTER TABLE Bridge_Activity_Group ADD CONSTRAINT fk_bridge_activity FOREIGN KEY (activity_sk) REFERENCES Dim_Activity(activity_sk);
ALTER TABLE Bridge_Activity_Group ADD CONSTRAINT fk_bridge_group_fk FOREIGN KEY (activity_group_sk) REFERENCES Dim_Activity_Group(activity_group_sk);


-- =========================================================
-- 5. VERIFICACIÓN DE LA ESTRUCTURA CREADA
-- =========================================================

-- Mostrar las tablas creadas
SELECT table_name FROM user_tables;